- name: Elastic Beats Installation
  hosts: LinuxServers
  roles: 
    - ansible-beats
  vars:
    beats_version: 7.16.3
    beat: metricbeat
    beat_conf:
      metricbeat.modules:
      - system
      - kafka
        enabled: true
